apps_internal/desk/urls.py
# coding: utf-8

from __future__ import unicode_literals, absolute_import

from django.conf.urls import patterns, url

from .views.redirect import DeskRedirectView
from .views.learn import DeskLearnView, DeskStartView
from .views.mentor_admin import DeskTeachView
from .views.pageadmin import PageAdminView
from .views.notification import NotificationView, NotificationUpdateView
from .views.courseadmin import CourseAdminView
from .views.courseentry_admin import CourseEntryAdminView
from .views.userprofile import UserProfileView
from .views.bookings import BookingsView

from .views.updates import CourseProductGroupUpdateView, PublicPagesUpdateView, \
    MentorsProfileUpdateView, UserProfileUpdateView, CourseProductGroupFieldUpdateView


urlpatterns = patterns('',
    #url(r'^profil$', DeskProfileView.as_view(), name='start' ),

    url(r'^benutzerprofil$', UserProfileView.as_view(), name='userprofile' ),

    url(r'^benachrichtigungen$', NotificationView.as_view(), name='notifications' ),
    url(r'^benachrichtigungen/(?P<pk>\d{1,4})/aendern$',
        NotificationUpdateView.as_view(), name='notificationsupdate' ),

    url(r'^unterrichten$', DeskTeachView.as_view(), name='teach' ),

    url(r'^lernen$', DeskLearnView.as_view(), name='learn' ),

    #url(r'^start$', DeskStartView.as_view(), name='start' ),

    url(r'^webseite$', PageAdminView.as_view(), name='pageadmin' ),

    url(r'^lektorat$', CourseAdminView.as_view(), name='courseadmin' ),

    url(r'^kurszugang-admin$', CourseEntryAdminView.as_view(), name='courseentry_admin' ),

    url(r'^kursbuchungen$', BookingsView.as_view(), name='bookings' ),

    url(r'^redirect$', DeskRedirectView.as_view(), name='redirect' ),

    url(r'^produktgruppe/(?P<pk>\d{1,4})/update$', CourseProductGroupUpdateView.as_view(),
        name='updategroup' ),
    url(r'^produktgruppenfeld/(?P<pk>\d{1,4})/update$', CourseProductGroupFieldUpdateView.as_view(),
        name='updategroupfield' ),
    url(r'^mentor/(?P<pk>\d{1,4})/update$',
        MentorsProfileUpdateView.as_view(),
        name='updatementor' ),

    url(r'^seite/(?P<pk>\w{1,20})/update$',
        PublicPagesUpdateView.as_view(),
        name='updatepage' ),

    url(r'^benutzerdaten/(?P<pk>\w{1,20})/update$',
        UserProfileUpdateView.as_view(),
        name='updateprofile' ),

)

mentoki/urls.py
# -*- coding: utf-8 -*-

"""
urls for mentoki
"""

from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.views.generic.base import TemplateView
from django.conf import settings
from django.views.defaults import *
from django.conf.urls import url, include
from django.contrib.sitemaps import views
from django.http import HttpResponsePermanentRedirect
from django.core.urlresolvers import reverse


from django_downloadview import ObjectDownloadView

from apps_data.material.models.material import Material

from .views import PublicViewSitemap, CoursesViewSitemap, \
    MentorsViewSitemap, StaticViewSitemap, CourseListViewSitemap

# for the download of files
download = ObjectDownloadView.as_view(model=Material, file_field='file')

from apps_public.newsletter.feeds import LatestNewsletterFeed

sitemaps = {
    'mentoki': PublicViewSitemap(),
    'homepage': StaticViewSitemap(),
    'kurse': CoursesViewSitemap(),
    'mentoren': MentorsViewSitemap(),
    'kurslisten': CourseListViewSitemap
}


# The Admin Site
urlpatterns = i18n_patterns('',

    # admin urls
    url(r'^admin/',
        include(admin.site.urls)),

    (r'^mail-queue/', include('mailqueue.urls')),
)


# seo
urlpatterns += i18n_patterns('',

    # robots
    (r'^robots\.txt/$',
        TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),

    (r'^googleb739bc2feb0d0b27\.html/$',
        TemplateView.as_view(template_name='googleb739bc2feb0d0b27.html')),

    (r'^kurse/googleb739bc2feb0d0b27\.html/$',
        TemplateView.as_view(template_name='googleb739bc2feb0d0b27.html')),

    #sitemaps
    url(r'^sitemap\.xml$', views.index, {'sitemaps': sitemaps}),
    url(r'^sitemap-(?P<section>.+)\.xml$', views.sitemap, {'sitemaps': sitemaps}),
)


# Public urls
urlpatterns += i18n_patterns('',

    # courseevent offers
    url(r'^checkout/',
        include('apps_public.checkout.urls', namespace='checkout')),

    # courseevent offers
    url(r'^kurse/',
        include('apps_public.storefront.urls', namespace='storefront')),

    # contact
    url(r'^kontakt/',
        include('apps_public.contact.urls', namespace='contact')),

    url(r'^kontakt',
        include('apps_public.contact.urls', namespace='contact')),

    # file newsletter ...
    url(r'^newsletter/',
        include('apps_public.newsletter.urls', namespace='newsletter')),

    # feed
    url(r'^feed/$',
        LatestNewsletterFeed(),
        name='feed'),
)


# User Account urls
urlpatterns += i18n_patterns('',

    # desk: startpoint for all activities
    url(r'^schreibtisch/',
        include('apps_internal.desk.urls', namespace='desk')),

    url(r'^accounts/', include('allauth.urls')),

)

# Data urls
urlpatterns += i18n_patterns('',

    # lesson data urls
    url(r'^unterricht/',
        include('apps_data.lesson.urls', namespace='lesson')),

    url(r'^kurseintern/',
        include('apps_data.courseevent.urls', namespace='courseevent')),
)


# Classroom urls
urlpatterns += i18n_patterns('',

    # classroom
    url(r'^(?P<slug>[a-z0-9_-]+)/klassenzimmer/',
        include('apps_internal.classroom.urls', namespace='classroom')),
)


# teachers dashboard
urlpatterns += i18n_patterns('',

    # coursebackend
    url(r'^(?P<course_slug>[a-z0-9_-]+)/kursvorbereitung/',
        include('apps_internal.coursebackend.urls', namespace='coursebackend')),
)


# utilities
urlpatterns += i18n_patterns('',

    url(r'^download/(?P<slug>[a-zA-Z0-9_-]+)/$',
        download, name="download"),

    # file markdown ...
    url(r'^markdown/',
        include('django_markdown.urls')),

    # froala editor
    url(r'^froala_editor/',
        include('froala_editor.urls')),

)

# utilities
urlpatterns += i18n_patterns('',
    # homepage
    url(r'^',
        include('apps_public.home.urls', namespace='home')),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.STATIC_ROOT,
        }),
)

# urls or settings
handler500 = 'mentoki.views.server_error'
handler503 = 'mentoki.views.maintenance_mode'

apps_internal/classroom/views/announcement.py
# -*- coding: utf-8 -*-

"""
These views show announcements in the classroom. Announcements are
the way a teachers adresses his students. They are listed by date.
They are written published in the backend of the course.

Logging: no logging required since nothing is written to the database here.
"""

from __future__ import unicode_literals

from django.views.generic import TemplateView, DetailView

from apps_data.courseevent.models.announcement import Announcement

from .mixins.base import ClassroomMenuMixin, AuthClassroomAccessMixin


class AnnouncementListView(
    AuthClassroomAccessMixin,
    ClassroomMenuMixin,
    TemplateView):
    """
    Announcements are listed in the classroom:
    announcements are chosen for a courseevent and only if they are published,
    but not archived.
    """
    def get_context_data(self, **kwargs):
        context = super(AnnouncementListView, self).get_context_data(**kwargs)

        context ['announcements'] = \
            Announcement.objects.published_in_class(courseevent =
                                                    context['courseevent'])

        return context


class AnnouncementDetailView(
    AuthClassroomAccessMixin,
    ClassroomMenuMixin,
    DetailView):
    """
    This shows a published not archived announcement in the
    classroom in detail.
    """
    model = Announcement
    context_object_name ='announcement'

apps_internal/classroom/views/classlesson.py
# coding: utf-8

from __future__ import unicode_literals, absolute_import

from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView, FormView, DetailView

from apps_data.courseevent.models.menu import ClassroomMenuItem
from apps_data.lesson.models.classlesson import ClassLesson

from .mixins.base import ClassroomMenuMixin, AuthClassroomAccessMixin


class ClassLessonStartView(
    AuthClassroomAccessMixin,
    ClassroomMenuMixin,
    TemplateView):
    """
    Shows all classlessons that are published in the class (have a menu entry in the classroom menu)
    """
    def get_context_data(self, **kwargs):
        context = super(ClassLessonStartView, self).get_context_data(**kwargs)

        context['lesson_items'] = \
            ClassroomMenuItem.objects.lessons_for_courseevent(
                courseevent=context['courseevent'])

        return context


class ClassLessonDetailView(
    AuthClassroomAccessMixin,
    ClassroomMenuMixin,
    TemplateView):
    """
    Show classlesson in Detail
    List all classlesson-steps of a lesson (they are all published along with the lesson)
    """
    def get_context_data(self, **kwargs):
        context = super(ClassLessonDetailView, self).get_context_data(**kwargs)

        lesson = get_object_or_404(ClassLesson, pk=self.kwargs['pk'])

        context['lesson'] = lesson
        context['breadcrumbs'] = lesson.get_published_breadcrumbs_with_self
        context['next_node'] = lesson.get_next_sibling_published
        context['previous_node'] = lesson.get_previous_sibling_published
        context['lessonsteps'] = lesson.get_children()

        return context

apps_internal/classroom/views/classlessonstep.py
# coding: utf-8

from __future__ import unicode_literals, absolute_import

from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView, DetailView

from apps_data.courseevent.models.homework import StudentsWork,Comment
from apps_data.lesson.models.classlesson import Question
from apps_data.lesson.models.classlesson import ClassLesson

from .mixins.base import ClassroomMenuMixin, AuthClassroomAccessMixin


class LessonStepContextMixin(object):
    """
    adds the homework to the context
    """
    def get_context_data(self, **kwargs):
        context = super(LessonStepContextMixin, self).get_context_data(**kwargs)

        lessonstep = get_object_or_404(ClassLesson, pk=self.kwargs['pk'])
        context['lessonstep'] = lessonstep
        context['breadcrumbs'] = lessonstep.get_published_breadcrumbs_with_self
        context['next_node'] = lessonstep.get_next_sibling()
        context['previous_node'] = lessonstep.get_previous_sibling()

        return context


class ClassLessonStepDetailView(
    AuthClassroomAccessMixin,
    ClassroomMenuMixin,
    LessonStepContextMixin,
    TemplateView):
    """
    Shows one classlesson-step
    """
    def get_context_data(self, **kwargs):
        context = super(ClassLessonStepDetailView, self).get_context_data(**kwargs)
        lessonstep = context['lessonstep']
        if lessonstep.is_homework:
            context['studentsworks'] = \
                StudentsWork.objects.turnedin_homework(homework=lessonstep)
        if lessonstep.allow_questions:
            context['questions'] = \
                Question.objects.question_to_lessonstep(classlessonstep=lessonstep)
        return context


class StudentsWorkPublicListView(
    AuthClassroomAccessMixin,
    ClassroomMenuMixin,
    LessonStepContextMixin,
    TemplateView):
    """
    Shows published students works
    """
    def get_context_data(self, **kwargs):
        context = super(StudentsWorkPublicListView, self).get_context_data(**kwargs)

        if context['lessonstep'].is_homework:
                context['studentsworks'] = \
                    StudentsWork.objects.turnedin_homework(homework=context['lessonstep'])

        return context


class StudentsWorkPrivateListView(
    AuthClassroomAccessMixin,
    ClassroomMenuMixin,
    LessonStepContextMixin,
    TemplateView):
    """
    Shows private students works
    """
    def get_context_data(self, **kwargs):
        context = super(StudentsWorkPrivateListView, self).get_context_data(**kwargs)

        if context['lessonstep'].is_homework:
                context['studentsworks'] = \
                    StudentsWork.objects.unpublished_homework(homework=context['lessonstep'],
                                                              user=self.request.user)

        return context


class StudentsWorkContextMixin(object):
    """
    adds the homework to the context
    """
    def get_context_data(self, **kwargs):
        context = super(StudentsWorkContextMixin, self).get_context_data(**kwargs)

        context['comments'] = \
            Comment.objects.comment_to_studentswork(studentswork=context['studentswork'])

        return context


class StudentsWorkDetailView(
    AuthClassroomAccessMixin,
    ClassroomMenuMixin,
    LessonStepContextMixin,
    StudentsWorkContextMixin,
    DetailView):
    """
    shows detail of a students work, that is published in the homework section
    """
    model = StudentsWork
    pk_url_kwarg = 'work_pk'
    context_object_name ='studentswork'

apps_internal/classroom/views/forum.py
# coding: utf-8

from __future__ import unicode_literals, absolute_import

from django.shortcuts import get_object_or_404

from django.views.generic import TemplateView

from apps_data.courseevent.models.forum import Forum, Thread

from .mixins.base import ClassroomMenuMixin, AuthClassroomAccessMixin


class ForumStartView(
    AuthClassroomAccessMixin,
    ClassroomMenuMixin,
    TemplateView):
    """
    shows all forums published in the classroom (published means a menu entry exists
    """
    def get_context_data(self, **kwargs):
        context = super(ForumStartView, self).get_context_data(**kwargs)

        context['nodes'] = Forum.objects.published_forums(
            courseevent=context['courseevent'])

        return context


class ForumDetailView(
    AuthClassroomAccessMixin,
    ClassroomMenuMixin,
    TemplateView):
    """
    show one forum
    """
    def get_context_data(self, **kwargs):
        context = super(ForumDetailView, self).get_context_data(**kwargs)

        forum = get_object_or_404(Forum, pk=self.kwargs['pk'])

        context['forum'] = forum
        context['breadcrumbs'] = forum.get_published_breadcrumbs_with_self
        context['nodes'] = forum.get_descendants()

        if forum.can_have_threads:
            context['threads'] = Thread.objects.filter(forum=forum)
        return context


class ForumRecentView(
    AuthClassroomAccessMixin,
    ClassroomMenuMixin,
    TemplateView):
    """
    show all recent forum contributions (threads and posts)
    """
    def get_context_data(self, **kwargs):
        context = super(ForumRecentView, self).get_context_data(**kwargs)

        context['contributions'] = Thread.objects.recent_published_contributions(
            courseevent=context['courseevent'])
        return context

apps_internal/classroom/views/lesson.py
# coding: utf-8

from __future__ import unicode_literals, absolute_import

from django.shortcuts import get_object_or_404

from vanilla import TemplateView

from apps_data.lesson.models.classlesson import ClassLesson

from .mixins.base import ClassroomMenuMixin


class LessonStartView(ClassroomMenuMixin, TemplateView):
    """
    Shows one lesson-step
    """
    def get_context_data(self, **kwargs):
        context = super(LessonStartView, self).get_context_data(**kwargs)

        context['nodes'] = \
            ClassLesson.objects.lessons_for_courseevent(courseevent=context['courseevent'])

        return context


class LessonBlockDetailView(ClassroomMenuMixin, TemplateView):
    """
    List all lesson-steps of a lesson
    """
    def get_context_data(self, **kwargs):
        context = super(LessonBlockDetailView, self).get_context_data(**kwargs)

        lessonblock = get_object_or_404(ClassLesson, pk=self.kwargs['pk'])

        context['lessonblock'] = lessonblock
        context['lessons'] = lessonblock.get_published_children(courseevent=context['courseevent'])

        return context


class LessonDetailView(ClassroomMenuMixin, TemplateView):
    """
    List all lesson-steps of a lesson
    """
    def get_context_data(self, **kwargs):
        context = super(LessonDetailView, self).get_context_data(**kwargs)

        lesson = get_object_or_404(ClassLesson, pk=self.kwargs['pk'])

        context['lesson'] = lesson
        context['breadcrumbs'] = lesson.get_ancestors()
        context['next_lesson'] = lesson.get_next_sibling()
        context['previous_lesson'] = lesson.get_previous_sibling()
        context['nodes'] = lesson.get_tree_with_material
        context['lessonsteps'] = lesson.get_children()

        return context


class LessonStepDetailView(ClassroomMenuMixin, TemplateView):
    """
    Shows one lesson-step
    """
    def get_context_data(self, **kwargs):
        context = super(LessonStepDetailView, self).get_context_data(**kwargs)

        lessonstep = get_object_or_404(ClassLesson, pk=self.kwargs['pk'])

        context['lessonstep'] = lessonstep
        context['breadcrumbs'] = lessonstep.get_ancestors()
        context['next_lessonstep'] = lessonstep.get_next_sibling()
        context['previous_lessonstep'] = lessonstep.get_previous_sibling()
        print context['lessonstep']
        print context['lessonstep'].materials.all()
        #context['materials'] = lessonstep.get_material

        return context

apps_internal/classroom/templates/classroom/_control_fulltext.html
<div class="item">
    <div class="ui checkbox" id="expandcontent">
        <input type="checkbox">
        <label>den ganzen Text anzeigen</label>
    </div>
</div>

apps_internal/classroom/templates/classroom/_control_structure.html
<div class="item">
    <div class="ui checkbox" id="showdescriptions">
        <input type="checkbox">
        <label>Struktur anzeigen</label>
    </div>
</div>

apps_internal/classroom/templates/classroom/_control_worklinks.html
<div class="item">
    <div class="ui checkbox" id="worklinks">
        <input type="checkbox" id="checkbox_work">
        <label>Bearbeitungs-Links</label>
    </div>
</div>

apps_internal/classroom/templates/classroom/_item_menu_representation.html
{% load activelink %}
{% load fontawesome %}

{% if item.item_type == item.MENU_ITEM_TYPE.forum_item %}
    {% url 'classroom:forum:detail' slug=es pk=item.forum_id as item_url %}
{% elif item.item_type == item.MENU_ITEM_TYPE.lesson_item %}
    {% url 'classroom:classlesson:lesson' slug=es pk=item.classlesson_id as item_url %}
{% elif item.item_type == item.MENU_ITEM_TYPE.lessonstep_item %}
    {% url 'classroom:classlesson:step' slug=es pk=item.classlesson_id as item_url %}
{% elif item.item_type == item.MENU_ITEM_TYPE.announcements_item %}
    {% url 'classroom:announcement:list' slug=es as item_url %}
{% elif item.item_type == item.MENU_ITEM_TYPE.participants_item %}
    {% url 'classroom:participant:list' slug=es as item_url %}
{% elif item.item_type == item.MENU_ITEM_TYPE.last_posts_item %}
    {% url 'classroom:forum:newposts' slug=es as item_url %}
{% elif item.item_type == item.MENU_ITEM_TYPE.private_item %}
    {% url 'classroom:studentswork:list' slug=es as item_url %}
{% endif %}

<a class="item
{% if item_url %}
    {% ifstartswith item_url %}active{% endifstartswith %}"  style="font-size:1.1em;"
    href="{{ item_url }}
{% endif %}
">
        {% if item.icon %}
            {{ item.icon.as_html }}
        {% endif %}
    {{ item.display_title }}
    <br>
</a>

apps_internal/classroom/templates/classroom/_menu.html
{% load activelink %}
{% load i18n %}

{% url "account_logout" as logout_url %}
{% url 'desk:learn' as desk_url %}
{% url 'coursebackend:menu:preview' course_slug=cs slug=es as coursebackend_url %}
{% url 'coursebackend:courseevent:detail' course_slug=cs slug=es as checklist_url %}

<div class="ui fluid vertical menu" id="coursebackend_menu">

    <div class="header item huge" style="font-size:1.5em;">
        Hallo {{ user.username }}!
    </div>
    <a  href="{% url 'desk:learn' %}" class="item" style="font-size:1.1em;">
        Zurück zum Schreibtisch
    </a>

    <a href="{{ logout_url }}" class="item" style="font-size:1.1em;">
        Ausloggen
    </a>


    {% if request.user in course.teachers or request.user.is_superuser %}

    <div class="header item huge" style="font-size:1.5em;">
        Für Lehrer:
    </div>


        <a class="item"  style="font-size:1.1em;"
        href="{{ coursebackend_url }}">
          Menü einrichten<i class="wrench icon"></i>
        </a>

        <!-- work link in coursebackend -->
        <a href="{{ checklist_url }}" class="item" style="font-size:1.1em;">
            Zur Checkliste<i class="rocket icon green"></i>
        </a>

    {% endif %}

    <div class="header item huge" style="font-size:1.5em;">
        {{ courseevent.title }}:
    </div>

    {% for item in menu_items %}

         {% if item.item_type == item.MENU_ITEM_TYPE.header_item %}
            <div class="header huge item" style="font-size:1.2em;">
                {{ item.display_title }}
            </div>
         {% else %}
            {% include 'classroom/_item_menu_representation.html' %}
         {% endif %}
    {% endfor %}

</div>

apps_internal/classroom/templates/classroom/_menu_top.html
{% url 'coursebackend:classlesson:copy'  slug=es course_slug=cs as copy_url %}

{% url 'coursebackend:courseevent:detail' course_slug=cs slug=es as courseevent_url %}
{% url 'coursebackend:participant:list' course_slug=cs slug=es as participants_url %}
{% url 'coursebackend:forum:list' course_slug=cs slug=es as forum_url %}
{% url 'coursebackend:announcement:list' course_slug=cs slug=es as announcements_url %}
{% url 'coursebackend:menu:preview' course_slug=cs slug=es as menu_url %}
{% url "coursebackend:lesson:start" course_slug=cs as lesson_url %}

{% url 'coursebackend:classlesson:start' course_slug=cs slug=es as classlesson_url %}
{% url 'coursebackend:classlesson:copy' course_slug=cs slug=es as lessoncopy_url %}
{% url 'coursebackend:course:detail' course_slug=cs as course_url %}
{% url 'coursebackend:lesson:start' course_slug=cs as lesson_url %}
{% url 'coursebackend:material:list' course_slug=cs as material_url %}
{% url 'classroom:start' slug=es as classroom_url %}

<!-- copy lessons -->
{% if url_name != 'copy' %}

{% endif %}
{% url 'coursebackend:courseevent:detail' course_slug=cs slug=es as checklist_url %}


<!-- work link in coursebackend -->
<a href="{{ copy_url }}" class="item
">
    <i class="icon copy  purple"></i>
</a>

<a href="{{ courseevent_url }}" class="item
" >
    <i class="rocket icon green"></i>
</a>

<a class="item
" href="{{ menu_url }}">
    <i class="sidebar icon blue"></i>
</a>

<a class="item
" href="{{ classlesson_url }}">
    <i class="book icon blue"></i>
</a>
<a class="item
" href="{{ lesson_url }}">
    <i class="book icon purple"></i>
</a>
<a class="item
" href="{{ announcements_url }}">
    <i class="announcement icon blue"></i>
</a>
<a class="item
" href="{{ forum_url }}">
    <i class="comments outline blue icon "></i>
</a>
<a class="item
" href="{{ participants_url }}">
    <i class="users icon blue"></i>
</a>
<a class="item
 active
" href="{{ classroom_url }}">
    <i class="student icon teal"></i>
</a>

apps_internal/classroom/templates/classroom/_popup_menu_classroom.html
{% load activelink %}

<div class="ui popup bottom fluid left transition hidden"  style="max-width:400px;">

    <div class="ui one column relaxed grid">

        <div class="column sixteen wide">

            <h4 class="ui header" id="coursebackend_menu_header">Kursereignis {{ courseevent.title }}</h4>

            <div class="ui link list">

                {% for item in menu_items_shortlinks %}

                    {% include 'classroom/_item_menu_representation.html' %}

                {% endfor %}

            </div>

        </div>

    </div>

</div>

apps_internal/classroom/templates/classroom/base.html
{% extends "base/base_pusher.html" %}
{% load activelink %}


{% block background_image %}background-image: url('/static/img/30520566_l_lighter.jpg');{% endblock %}

{% block page_header %}
     <h2 style="
         padding:20px;
         margin:0px -20px;
         opacity:0.5;
         background:white;
         ">
         Kurs {{ courseevent.title }}: {{ courseevent.teachersrecord }}
     </h2>

{% endblock %}

{% block css_breadcrumbs %}classroom_background{% endblock %}

{% block stackable_menu %}

    <div class="ui stackable menu">

        <a class="item" id="sidebar_button">
            <i class="sidebar icon"></i>
            Menu
        </a>

        <a class="browse item">
            Klassenzimmer
            <i class="dropdown icon"></i>
        </a>

        {% include 'classroom/_popup_menu_classroom.html' %}
        {% url 'coursebackend:courseevent:detail' course_slug=cs slug=es as checklist_url %}
        {% if request.user in course.teachers or request.user.is_superuser %}

                 {% include 'classroom/_menu_top.html' %}
        {% endif %}

    </div>

{% endblock %}

{% block sidebar_menu %}

    <!-- BLOCK: sidebar: filled! -->

    {% include 'classroom/_menu.html' %}

{% endblock %}